version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
    labels: ["actions"]
    # only needed for non-default branch
    #target-branch: "develop"
    ignore:
      # Offical actions have moving tags like v1
      # that are used, so they don't need updates here
      - dependency-name: "actions/*"
