scanner:
    diff_only: True
    linter: flake8  # Other option is pycodestyle

no_blank_comment: False  # If True, no comment is made on PR without any errors.
descending_issues_order: True  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

[flake8]
exclude =
    .git,
    .github,
    __pycache__,
    build,
    dist,
    src,
    inc,

max-line-length = 84  # match .flake8 cfg file
