name: ripc-test

dependencies:
  - python={{ get_env("PY_VER", default="3.10") }}
  - cmake>=3.18
  - ninja
  - gcc_linux-64
  - gxx_linux-64
  - pip
  - make  # [unix]
  - pkg-config  # [unix]
  - json-c=0.15
  - libhiredis=1.0.0
  - gtest
  - lcov
  - gcovr
