Redis-IPC: src/redis_ipc.h File Reference
redis_ipc.h File Reference
#include <sys/types.h>
#include <json-c/json.h>
Macros
#define RIPC_OK 0
#define RIPC_FAIL (-1)
#define RIPC_CONF_PATH "./redis_ipc.conf"
#define RIPC_MAX_DEBUG_LEN 1024
#define RIPC_MAX_IPC_PATH_LEN 128
#define RIPC_RUNTIME_DIR "/tmp/redis-ipc"
#define RIPC_SERVER_PATH RIPC_RUNTIME_DIR "/socket"
Enumerations
enum {
RIPC_DBG_ERROR, RIPC_DBG_ALERT, RIPC_DBG_WARN, RIPC_DBG_INFO,
RIPC_DBG_NOISY, RIPC_DBG_EXTRA_NOISY
}
Functions
int redis_ipc_init (const char *this_component, const char *this_thread)
int redis_ipc_cleanup (pid_t tid)
int get_debug_verbosity ()
int stderr_debug_is_enabled ()
json_object * redis_ipc_send_command_blocking (const char *dest_component, const char *subqueue, json_object *command, unsigned int timeout)
json_object * redis_ipc_receive_command_blocking (const char *subqueue, unsigned int timeout)
int redis_ipc_send_result (const json_object *completed_command, json_object *result)
int redis_ipc_write_setting (const char *owner_component, const json_object *fields)
json_object * redis_ipc_read_setting (const char *owner_component)
int redis_ipc_write_setting_field (const char *owner_component, const char *field_name, const char *field_value)
char * redis_ipc_read_setting_field (const char *owner_component, const char *field_name)
int redis_ipc_write_status (const json_object *fields)
json_object * redis_ipc_read_status (const char *owner_component)
int redis_ipc_write_status_field (const char *field_name, const char *field_value)
char * redis_ipc_read_status_field (const char *owner_component, const char *field_name)
int redis_ipc_send_event (const char *subchannel, json_object *message)
int redis_ipc_subscribe_events (const char *component, const char *subchannel)
int redis_ipc_unsubscribe_events (void)
int redis_ipc_send_debug (unsigned int debug_level, const char *format,...)
int redis_ipc_subscribe_debug (const char *component)
int redis_ipc_unsubscribe_debug (void)
json_object * redis_ipc_get_message_blocking (void)
Macro Definition Documentation
RIPC_CONF_PATH
#define RIPC_CONF_PATH "./redis_ipc.conf"
Definition at line 34 of file redis_ipc.h.
RIPC_FAIL
#define RIPC_FAIL (-1)
Definition at line 30 of file redis_ipc.h.
RIPC_MAX_DEBUG_LEN
#define RIPC_MAX_DEBUG_LEN 1024
Definition at line 39 of file redis_ipc.h.
RIPC_MAX_IPC_PATH_LEN
#define RIPC_MAX_IPC_PATH_LEN 128
Definition at line 42 of file redis_ipc.h.
RIPC_OK
#define RIPC_OK 0
Definition at line 29 of file redis_ipc.h.
RIPC_RUNTIME_DIR
#define RIPC_RUNTIME_DIR "/tmp/redis-ipc"
Definition at line 49 of file redis_ipc.h.
RIPC_SERVER_PATH
#define RIPC_SERVER_PATH RIPC_RUNTIME_DIR "/socket"
Definition at line 51 of file redis_ipc.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RIPC_DBG_ERROR
RIPC_DBG_ALERT
RIPC_DBG_WARN
RIPC_DBG_INFO
RIPC_DBG_NOISY
RIPC_DBG_EXTRA_NOISY
Definition at line 21 of file redis_ipc.h.
      { RIPC_DBG_ERROR,
        RIPC_DBG_ALERT,
        RIPC_DBG_WARN,
        RIPC_DBG_INFO,
        RIPC_DBG_NOISY,
        RIPC_DBG_EXTRA_NOISY };
Function Documentation
get_debug_verbosity()
int get_debug_verbosity ()
Definition at line 220 of file redis_ipc.c.
 {
     return 5;
 }
Referenced by redis_ipc_send_debug().
redis_ipc_cleanup()
int redis_ipc_cleanup (pid_t tid)
Definition at line 205 of file redis_ipc.c.
 {
     struct redis_ipc_per_thread *next_info = redis_ipc_info;
     int ret = RIPC_FAIL;
     if (next_info != NULL && next_info->tid == tid)
     {
         cleanup_per_thread_info(next_info);
         ret = RIPC_OK;
     }
     return ret;
 }
References cleanup_per_thread_info(), redis_ipc_info, RIPC_FAIL, RIPC_OK, and redis_ipc_per_thread::tid.
redis_ipc_get_message_blocking()
json_object* redis_ipc_get_message_blocking (void)
Definition at line 1233 of file redis_ipc.c.
 {
     json_object *message = NULL;
     redisReply *reply = NULL;
     const char *message_str = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_get_channel_message_finish;
     // block until a message is available
     ret = redisGetReply(thread_info->redis_state, &reply);
     if (ret != REDIS_OK)
     {
         // must reconnect to redis server after an error
         redisFree(thread_info->redis_state);
         thread_info->redis_state = redisConnectUnix(RIPC_SERVER_PATH);
         goto redis_get_channel_message_finish;
     }
     // extract message from reply object
     //
     // reply should be an array:
     //   string "pmessage"
     //   string <psubscribe pattern>
     //   string <sending channel>
     //   string <message> ** entry of interest
     if (reply->type != REDIS_REPLY_ARRAY)
         goto redis_get_channel_message_finish;
     if (reply->element[3]->type != REDIS_REPLY_STRING)
         goto redis_get_channel_message_finish;
     message_str = reply->element[3]->str;
     if (stderr_debug_is_enabled())
     {
         fprintf(stderr, "[MESSAGE] %s\n", message_str);
     }
     // parse message back into json object
     message = json_tokener_parse(message_str);
 redis_get_channel_message_finish:
     if (reply != NULL)
         freeReplyObject(reply);
     return message;
 }
References get_per_thread_info(), redis_ipc_per_thread::redis_state, RIPC_FAIL, RIPC_SERVER_PATH, and stderr_debug_is_enabled().
redis_ipc_init()
int redis_ipc_init (const char * this_component, const char * this_thread)
Definition at line 149 of file redis_ipc.c.
 {
     struct redis_ipc_per_thread *new_info = NULL;
     char result_queue_path[RIPC_MAX_IPC_PATH_LEN];
     int ret = RIPC_FAIL;
     new_info = calloc(1, sizeof(struct redis_ipc_per_thread));
     if (new_info == NULL)
         return RIPC_FAIL;  // nothing to clean up before returning
     // component is name for all threads/processes in same subsystem,
     // thread is uniquely (non-random) assigned name for this thread,
     new_info->component = strdup(this_component);
     new_info->thread = strdup(this_thread);
     if (new_info->component == NULL || new_info->thread == NULL)
         goto redis_ipc_init_failed;
     // tid is OS thread ID number
     new_info->tid = gettid();
     // path to redis server socket can be overridden from environment
     new_info->redis_socket_path = getenv("RIPC_SERVER_PATH");
     if (new_info->redis_socket_path == NULL)
         new_info->redis_socket_path = RIPC_SERVER_PATH;
     // each thread gets its own redis connection
     new_info->redis_state = redisConnectUnix(new_info->redis_socket_path);
     if (new_info->redis_state == NULL || new_info->redis_state->err)
         goto redis_ipc_init_failed;
     // each thread gets its own results queue in redis
     memset(result_queue_path, 0, sizeof(result_queue_path));
     ret = ipc_path(result_queue_path, sizeof(result_queue_path),
                    RPC_TYPE_RESULT, this_component, this_thread);
     if (ret != RIPC_OK)
         goto redis_ipc_init_failed;
     new_info->result_queue_path = strdup(result_queue_path);
     if (new_info->result_queue_path == NULL)
         goto redis_ipc_init_failed;
     redis_ipc_info = new_info;
     return RIPC_OK;
 redis_ipc_init_failed:
     if (stderr_debug_is_enabled())
     {
         fprintf(stderr, "[ERROR] redis_ipc_init failed for thread %s\n", this_thread);
     }
     cleanup_per_thread_info(new_info);
     safe_free(new_info);
     return RIPC_FAIL;
 }
References cleanup_per_thread_info(), redis_ipc_per_thread::component, gettid(), ipc_path(), redis_ipc_info, redis_ipc_per_thread::redis_socket_path, redis_ipc_per_thread::redis_state, redis_ipc_per_thread::result_queue_path, RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, RIPC_SERVER_PATH, RPC_TYPE_RESULT, safe_free, stderr_debug_is_enabled(), redis_ipc_per_thread::thread, and redis_ipc_per_thread::tid.
redis_ipc_read_setting()
json_object* redis_ipc_read_setting (const char * owner_component)
Definition at line 800 of file redis_ipc.c.
 {
     char setting_hash_path[RIPC_MAX_IPC_PATH_LEN];
     json_object *fields = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_read_setting_finish;
     // calculate name of setting hash belonging to specified component
     ret = ipc_path(setting_hash_path, sizeof(setting_hash_path),
                    RPC_TYPE_SETTING, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_read_setting_finish;
     // get all fields of setting hash
     fields = redis_read_hash(setting_hash_path);
 redis_ipc_read_setting_finish:
     return fields;
 }
References get_per_thread_info(), ipc_path(), redis_read_hash(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_SETTING.
redis_ipc_read_setting_field()
char* redis_ipc_read_setting_field (const char * owner_component, const char * field_name)
Definition at line 883 of file redis_ipc.c.
 {
     char setting_hash_path[RIPC_MAX_IPC_PATH_LEN];
     char *field_value = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_read_setting_field_finish;
     // calculate name of setting hash belonging to specified component
     ret = ipc_path(setting_hash_path, sizeof(setting_hash_path),
                    RPC_TYPE_SETTING, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_read_setting_field_finish;
     // get all fields of setting hash
     field_value = redis_read_hash_field(setting_hash_path, field_name);
 redis_ipc_read_setting_field_finish:
     return field_value;
 }
References get_per_thread_info(), ipc_path(), redis_read_hash_field(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_SETTING.
redis_ipc_read_status()
json_object* redis_ipc_read_status (const char * owner_component)
Definition at line 825 of file redis_ipc.c.
 {
     char status_hash_path[RIPC_MAX_IPC_PATH_LEN];
     json_object *fields = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_read_status_finish;
     // calculate name of status hash belonging to specified component
     ret = ipc_path(status_hash_path, sizeof(status_hash_path),
                    RPC_TYPE_STATUS, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_read_status_finish;
     // get all fields of status hash
     fields = redis_read_hash(status_hash_path);
 redis_ipc_read_status_finish:
     return fields;
 }
References get_per_thread_info(), ipc_path(), redis_read_hash(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_STATUS.
redis_ipc_read_status_field()
char* redis_ipc_read_status_field (const char * owner_component, const char * field_name)
Definition at line 908 of file redis_ipc.c.
 {
     char status_hash_path[RIPC_MAX_IPC_PATH_LEN];
     const char *field_value = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_read_status_field_finish;
     // calculate name of status hash belonging to specified component
     ret = ipc_path(status_hash_path, sizeof(status_hash_path),
                    RPC_TYPE_STATUS, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_read_status_field_finish;
     // get all fields of status hash
     field_value = redis_read_hash_field(status_hash_path, field_name);
 redis_ipc_read_status_field_finish:
     return field_value;
 }
References get_per_thread_info(), ipc_path(), redis_read_hash_field(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_STATUS.
redis_ipc_receive_command_blocking()
json_object* redis_ipc_receive_command_blocking (const char * subqueue, unsigned int timeout)
Definition at line 504 of file redis_ipc.c.
 {
     char command_queue_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     json_object *command = NULL;
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_receive_command_blocking_finish;
     // calculate name of own command queue
     ret = ipc_path(command_queue_path, sizeof(command_queue_path),
                    RPC_TYPE_COMMAND, thread_info->component, subqueue);
     if (ret != RIPC_OK)
         goto redis_ipc_receive_command_blocking_finish;
     // wait for entry from command queue
     command = redis_pop(command_queue_path, timeout);
     if (command != NULL && !json_object_is_type(command, json_type_object))
     {
         // commands are supposed to be hash objects, not whatever this thing is
         redis_ipc_send_debug(RIPC_DBG_ERROR, "redis_ipc_receive_command_blocking():"
                                  "invalid command '%s'",
                              json_object_get_string(command));
         json_object_put(command);
         command = NULL;
     }
 redis_ipc_receive_command_blocking_finish:
     return command;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_ipc_send_debug(), redis_pop(), RIPC_DBG_ERROR, RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_COMMAND.
redis_ipc_send_command_blocking()
json_object* redis_ipc_send_command_blocking (const char * dest_component, const char * subqueue, json_object * command, unsigned int timeout)
Definition at line 412 of file redis_ipc.c.
 {
     char command_queue_path[RIPC_MAX_IPC_PATH_LEN];
     char result_queue_path[RIPC_MAX_IPC_PATH_LEN];
     char id_buffer[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     json_object *result = NULL, *result_id_obj = NULL;
     const char *result_id_str = NULL;
     int ret = RIPC_FAIL, received_result = 0;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_send_command_blocking_finish;
     // calculate name of command queue belonging to specified component
     ret = ipc_path(command_queue_path, sizeof(command_queue_path),
                    RPC_TYPE_COMMAND, dest_component, subqueue);
     if (ret != RIPC_OK)
         goto redis_ipc_send_command_blocking_finish;
     // calculate name of own queue for receiving the result
     ret = ipc_path(result_queue_path, sizeof(result_queue_path),
                    RPC_TYPE_RESULT, thread_info->component, thread_info->thread);
     if (ret != RIPC_OK)
         goto redis_ipc_send_command_blocking_finish;
     // generate unique id used to match command and its result
     snprintf(id_buffer, sizeof(id_buffer), "%s-%s-%d-%u",
              thread_info->component, thread_info->thread,
              thread_info->tid, thread_info->command_ctr++);
     // append generated fields to command
     json_object_object_add(command, "results_queue",
                            json_object_new_string(result_queue_path));
     json_object_object_add(command, "command_id",
                            json_object_new_string(id_buffer));
     // push command onto queue
     ret = redis_push(command_queue_path, command);
     if (ret != RIPC_OK)
         goto redis_ipc_send_command_blocking_finish;
     // receive result
     while (!received_result)
     {
         // wait for entry from results queue
         result = redis_pop(result_queue_path, timeout);
         if (result != NULL && !json_object_is_type(result, json_type_object))
         {
             // results are supposed to be hash objects, not whatever this thing is
             redis_ipc_send_debug(RIPC_DBG_ERROR, "redis_ipc_send_command_blocking():"
                                  "invalid result '%s'", json_object_get_string(result));
             json_object_put(result);
             result = NULL;
         }
         if (result == NULL)
             goto redis_ipc_send_command_blocking_finish;
         // extract command id from received result
         result_id_obj = json_object_object_get(result, "command_id");
         if (result_id_obj == NULL)
             goto redis_ipc_send_command_blocking_finish;
         result_id_str = json_object_get_string(result_id_obj);
         if (result_id_str == NULL)
             goto redis_ipc_send_command_blocking_finish;
         // verify result matches submitted command
         if (strcmp(result_id_str, id_buffer) == 0)
         {
             received_result = 1;
         }
         else
         {
            redis_ipc_send_debug(RIPC_DBG_ERROR, "redis_ipc_send_command_blocking():"
                                    "received stale result id %s, want id %s",
                                 result_id_str, id_buffer);
         }
     }
 redis_ipc_send_command_blocking_finish:
     if (result == NULL || !json_object_is_type(result, json_type_object))
     {
         redis_ipc_send_debug(RIPC_DBG_ERROR, "redis_ipc_send_command_blocking():"
                                 "invalid result");
     }
     return result;
 }
References redis_ipc_per_thread::command_ctr, redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_ipc_send_debug(), redis_pop(), redis_push(), redis_ipc_per_thread::result_queue_path, RIPC_DBG_ERROR, RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, RPC_TYPE_COMMAND, RPC_TYPE_RESULT, redis_ipc_per_thread::thread, and redis_ipc_per_thread::tid.
redis_ipc_send_debug()
int redis_ipc_send_debug (unsigned int debug_level, const char * format, ...)
Definition at line 1015 of file redis_ipc.c.
 {
     char msg_buffer[RIPC_MAX_DEBUG_LEN];
     char debug_channel_path[RIPC_MAX_IPC_PATH_LEN];
     va_list argp;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     json_object *debug_obj = NULL;
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_send_debug_finish;
     // ignore if the debug level is higher than current verbosity
     if (debug_level > get_debug_verbosity())
     {
         return RIPC_OK;  // it's easy to successfully do nothing...
     }
     // calculate channel name
     ret = ipc_path(debug_channel_path, sizeof(debug_channel_path),
                    RPC_TYPE_DEBUG, thread_info->component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_send_debug_finish;
     // format message into string
     memset(msg_buffer, 0, sizeof(msg_buffer));
     va_start(argp, format);
     ret = format_debug_msg(msg_buffer, sizeof(msg_buffer), format, argp);
     va_end(argp);
     if (ret != RIPC_OK)
         goto redis_ipc_send_debug_finish;
     // generate debug object
     debug_obj = json_object_new_object();
     if (debug_obj == NULL)
         goto redis_ipc_send_debug_finish;
     json_object_object_add(debug_obj, "message",
                            json_object_new_string(msg_buffer));
     json_object_object_add(debug_obj, "level",
                            json_object_new_int(debug_level));
     // publish debug object
     ret = redis_publish(debug_channel_path, debug_obj);
 redis_ipc_send_debug_finish:
     json_object_put(debug_obj);  // safe to call even if NULL
     return ret;
 }
References redis_ipc_per_thread::component, format_debug_msg(), get_debug_verbosity(), get_per_thread_info(), ipc_path(), redis_publish(), RIPC_FAIL, RIPC_MAX_DEBUG_LEN, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_DEBUG.
Referenced by redis_ipc_receive_command_blocking(), redis_ipc_send_command_blocking(), and redis_ipc_send_result().
redis_ipc_send_event()
int redis_ipc_send_event (const char * subchannel, json_object * message)
Definition at line 961 of file redis_ipc.c.
 {
     char event_channel_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_send_event_finish;
     // calculate channel name
     ret = ipc_path(event_channel_path, sizeof(event_channel_path),
                    RPC_TYPE_EVENT, thread_info->component, subchannel);
     if (ret != RIPC_OK)
         goto redis_ipc_send_event_finish;
     // publish event object
     ret = redis_publish(event_channel_path, message);
 redis_ipc_send_event_finish:
     return ret;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_publish(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_EVENT.
redis_ipc_send_result()
int redis_ipc_send_result (const json_object * completed_command, json_object * result)
Definition at line 539 of file redis_ipc.c.
 {
     json_object *id_obj = NULL, *result_queue_obj = NULL;
     const char *id_str = NULL, *result_queue_path = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_send_result_finish;
     // extract name of result queue
     result_queue_obj = json_object_object_get(completed_command, "results_queue");
     if (result_queue_obj == NULL)
         goto redis_ipc_send_result_finish;
     result_queue_path = json_object_get_string(result_queue_obj);
     // extract command id
     id_obj = json_object_object_get(completed_command, "command_id");
     if (id_obj == NULL)
         goto redis_ipc_send_result_finish;
     id_str = json_object_get_string(id_obj);
     // append command id to result
     json_object_object_add(result, "command_id",
                            json_object_new_string(id_str));
     // push result onto queue
     ret = redis_push(result_queue_path, result);
 redis_ipc_send_result_finish:
     if (ret != RIPC_OK)
         redis_ipc_send_debug(RIPC_DBG_ERROR, "redis_ipc_send_result():"
                                 "could not send result for command %s",
                                 json_object_get_string(completed_command));
     return ret;
 }
References get_per_thread_info(), redis_ipc_send_debug(), redis_push(), redis_ipc_per_thread::result_queue_path, RIPC_DBG_ERROR, RIPC_FAIL, and RIPC_OK.
redis_ipc_subscribe_debug()
int redis_ipc_subscribe_debug (const char * component)
Definition at line 1133 of file redis_ipc.c.
 {
     char debug_channel_path[RIPC_MAX_IPC_PATH_LEN];
     const char *component_pattern = NULL;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_subscribe_debug_finish;
     // calculate channel name
     if (component == NULL)
     {
         // use wildcard to get all debug channels
         component_pattern = "*";
     }
     else
     {
         // exact match
         component_pattern = component;
     }
     ret = ipc_path(debug_channel_path, sizeof(debug_channel_path),
                    RPC_TYPE_DEBUG, component_pattern, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_subscribe_debug_finish;
     // publish debug object
     ret = redis_subscribe(debug_channel_path);
 redis_ipc_subscribe_debug_finish:
     return ret;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_subscribe(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_DEBUG.
redis_ipc_subscribe_events()
int redis_ipc_subscribe_events (const char * component, const char * subchannel)
Definition at line 1086 of file redis_ipc.c.
 {
     char event_channel_path[RIPC_MAX_IPC_PATH_LEN];
     char *component_pattern = NULL;
     size_t pattern_len = 0;
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_subscribe_events_finish;
     // calculate channel name
     if (component == NULL)
     {
         // use wildcard to get all event channels
         component_pattern = strdup("*");
     }
     else
     {
         if (subchannel == NULL)
         {
             // append wildcard to get all event channels for this component
             pattern_len = strlen(component)+2;
             component_pattern = calloc(1, pattern_len);
             snprintf(component_pattern, pattern_len, "%s%c", component, '*');
         }
         else
         {
             // exact match for both component and subchannel
             component_pattern = strdup(component);
         }
     }
     ret = ipc_path(event_channel_path, sizeof(event_channel_path),
                    RPC_TYPE_EVENT, component_pattern, subchannel);
     if (ret != RIPC_OK)
         goto redis_ipc_subscribe_events_finish;
     // publish event object
     ret = redis_subscribe(event_channel_path);
 redis_ipc_subscribe_events_finish:
     safe_free(component_pattern);
     return ret;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_subscribe(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, RPC_TYPE_EVENT, and safe_free.
redis_ipc_unsubscribe_debug()
int redis_ipc_unsubscribe_debug (void)
Definition at line 1209 of file redis_ipc.c.
 {
     char debug_channel_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_unsubscribe_debug_finish;
     ret = ipc_path(debug_channel_path, sizeof(debug_channel_path),
                    RPC_TYPE_DEBUG, "*", NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_unsubscribe_debug_finish;
     ret = redis_unsubscribe(debug_channel_path);
 redis_ipc_unsubscribe_debug_finish:
     return ret;
 }
References get_per_thread_info(), ipc_path(), redis_unsubscribe(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_DEBUG.
redis_ipc_unsubscribe_events()
int redis_ipc_unsubscribe_events (void)
Definition at line 1186 of file redis_ipc.c.
 {
     char event_channel_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_unsubscribe_events_finish;
     ret = ipc_path(event_channel_path, sizeof(event_channel_path),
                    RPC_TYPE_EVENT, "*", NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_unsubscribe_events_finish;
     ret = redis_unsubscribe(event_channel_path);
 redis_ipc_unsubscribe_events_finish:
     return ret;
 }
References get_per_thread_info(), ipc_path(), redis_unsubscribe(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_EVENT.
redis_ipc_write_setting()
int redis_ipc_write_setting (const char * owner_component, const json_object * fields)
Definition at line 635 of file redis_ipc.c.
 {
     char setting_hash_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_write_setting_finish;
     // verify this component is allowed to update settings
     if (!component_can_write_settings(thread_info->component))
         goto redis_ipc_write_setting_finish;
     // calculate name of setting hash corresponding to specified component
     ret = ipc_path(setting_hash_path, sizeof(setting_hash_path),
                    RPC_TYPE_SETTING, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_write_setting_finish;
     // update current setting hash with supplied values
     ret = redis_write_hash(setting_hash_path, fields);
 redis_ipc_write_setting_finish:
     return ret;
 }
References redis_ipc_per_thread::component, component_can_write_settings(), get_per_thread_info(), ipc_path(), redis_write_hash(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_SETTING.
redis_ipc_write_setting_field()
int redis_ipc_write_setting_field (const char * owner_component, const char * field_name, const char * field_value)
Definition at line 705 of file redis_ipc.c.
 {
     char setting_hash_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_write_setting_field_finish;
     // verify this component is allowed to update settings
     if (!component_can_write_settings(thread_info->component))
         goto redis_ipc_write_setting_field_finish;
     // calculate name of setting hash corresponding to specified component
     ret = ipc_path(setting_hash_path, sizeof(setting_hash_path),
                    RPC_TYPE_SETTING, owner_component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_write_setting_field_finish;
     // update current setting hash with supplied field
     ret = redis_write_hash_field(setting_hash_path, field_name, field_value);
 redis_ipc_write_setting_field_finish:
     return ret;
 }
References redis_ipc_per_thread::component, component_can_write_settings(), get_per_thread_info(), ipc_path(), redis_write_hash_field(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_SETTING.
redis_ipc_write_status()
int redis_ipc_write_status (const json_object * fields)
Definition at line 663 of file redis_ipc.c.
 {
     char status_hash_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_write_status_finish;
     // calculate name of own status hash
     ret = ipc_path(status_hash_path, sizeof(status_hash_path),
                    RPC_TYPE_STATUS, thread_info->component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_write_status_finish;
     // update current status hash with supplied values
     ret = redis_write_hash(status_hash_path, fields);
 redis_ipc_write_status_finish:
     return ret;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_write_hash(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_STATUS.
redis_ipc_write_status_field()
int redis_ipc_write_status_field (const char * field_name, const char * field_value)
Definition at line 734 of file redis_ipc.c.
 {
     char status_hash_path[RIPC_MAX_IPC_PATH_LEN];
     struct redis_ipc_per_thread *thread_info = get_per_thread_info();
     int ret = RIPC_FAIL;
     // make sure successful init has been performed
     if (thread_info == NULL)
         goto redis_ipc_write_status_field_finish;
     // calculate name of own status hash
     ret = ipc_path(status_hash_path, sizeof(status_hash_path),
                    RPC_TYPE_STATUS, thread_info->component, NULL);
     if (ret != RIPC_OK)
         goto redis_ipc_write_status_field_finish;
     // update current status hash with supplied field
     ret = redis_write_hash_field(status_hash_path, field_name, field_value);
 redis_ipc_write_status_field_finish:
     return ret;
 }
References redis_ipc_per_thread::component, get_per_thread_info(), ipc_path(), redis_write_hash_field(), RIPC_FAIL, RIPC_MAX_IPC_PATH_LEN, RIPC_OK, and RPC_TYPE_STATUS.
stderr_debug_is_enabled()
int stderr_debug_is_enabled ()
Definition at line 226 of file redis_ipc.c.
 {
     return 1;
 }
Referenced by redis_command(), redis_command_from_list(), redis_ipc_get_message_blocking(), redis_ipc_init(), redis_pop(), redis_read_hash(), redis_read_hash_field(), and validate_redis_reply().