{% set name = "redis-ipc" %}
{% set version = "0.0.3" %}
{% set soversion = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
    - json-c
    - libhiredis

  host:
    - redis-py
    - json-c
    - libhiredis
    - pthread-stubs

test:
  commands:
    - ldd ${PREFIX}/lib/libredis_ipc${SHLIB_EXT}  # [linux]
    - test -f ${PREFIX}/include/redis_ipc.h  # [unix]
    - test -f ${PREFIX}/lib/libredis_ipc${SHLIB_EXT}  # [osx]
    - echo "TODO - Pkg tests require redis server."

about:
  home: https://github.com/VCTLabs/redis-ipc
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: advanced IPC mechanism using redis

extra:
  recipe-maintainers:
    - sarnold
