name: choke

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
#  schedule:
#  - cron: '15 1 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Environment
      run: |
        bash -c set

    - name: Backports
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y -s ppa:nerdboy/embedded
        sudo apt-get install -y libjson-c-dev lcov
        sudo apt-get install -y libhiredis-dev gcovr redis-server
        sudo apt-get install -y valgrind libc6-dbg

    - name: Stop redis-server system service
      run: |
        sudo systemctl stop redis

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run tests with valgrind
      run: |
        tox -e grind
        tox -e tests
