name: CondaDev

on:
  workflow_dispatch:
  #push:
    #branches:
      #- master
      #- develop
  pull_request:

jobs:
  build:
    name: redis-ipc ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: ['3.7', '3.9']
        include:
          - os: 'ubuntu-latest'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'
          - os: 'macos-latest'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'

    steps:
    - uses: actions/checkout@v2

    - name: Configure Cache
      id: cache
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache and rebuild the env during the PR
        CACHE_NUMBER: 1
      with:
        path: |
          **/build
          **/ccache
          ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-${{ matrix.python-version }}-${{ github.ref }}-${{ env.CACHE_NUMBER }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        use-only-tar-bz2: true

    - name: Configure Conda Environment
      shell: bash -l {0}
      env:
        PY_VER: ${{ matrix.python-version }}
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install conda-devenv
        conda devenv

    - name: Build and test
      shell: bash -l {0}
      env:
        PY_VER: ${{ matrix.python-version }}
        #CC: ccache
        #CXX: ccache
      run: >
        source activate redis-ipc &&
        ctest
        --build-config "${{ matrix.build_type }}"
        --build-generator "${{ matrix.generator }}"
        --build-and-test . build
        --build-options -DRIPC_DISABLE_SOCK_TESTS=1 -DCCACHE_IGNORE=1
        --test-command ctest -V --build-config "${{ matrix.build_type }}"
