name: CondaDev

on:
  workflow_dispatch:
  #push:
    #branches:
      #- master
  #pull_request:

jobs:
  build:
    name: redis-ipc ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        # add these later, 'windows-2016', 'windows-2019'
        python-version: ['3.7', '3.9']
        include:
          - os: 'ubuntu-latest'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'
          - os: 'macos-latest'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'
          #- os: 'windows-2016'
            #generator: 'Visual Studio 15 2017 Win64'
            #build_type: 'Release'
          #- os: 'windows-2019'
            #generator: 'Visual Studio 16 2019'
            #build_type: 'Release'

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict

    - name: install prerequisites
      shell: pwsh
      run: >
        conda install
        cmake
        ninja
        pkg-config
        c-compiler
        cxx-compiler
        json-c
        libhiredis

    - name: print info
      shell: pwsh
      run: |
        conda info
        conda list

    - name: build and test
      shell: pwsh
      run: >
        ctest
        --build-config "${{ matrix.build_type }}"
        --build-generator "${{ matrix.generator }}"
        --build-and-test . build
        --build-options -DRIPC_DISABLE_SOCK_TESTS=1
        --test-command ctest -V --build-config "${{ matrix.build_type }}"
