name: Release

on:
  push:
    # release on tag push
    tags:
      - '*'

jobs:
  get_version:
    name: Get version info
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    outputs:
      version: ${{ steps.git_ver.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get package version
        id: git_ver
        run: |
          version=$(git describe --tags | sed -e "s|v||" -e "s|-g|+g|")
          echo "Version from git: ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

  packaging:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs: [get_version]

    strategy:
      fail-fast: false
      matrix:
        name: [
          x64_bookworm,
          x64_trixie,
          x64_sid,
        ]

        include:
          - name: x64_bookworm
            dist: bookworm

          - name: x64_trixie
            dist: trixie

          - name: x64_sid
            dist: sid

    steps:
      - name: Check github variables
        env:
          VERSION: ${{ needs.get_version.outputs.version }}
        run: |
          echo "Package version from git: ${VERSION}"

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install deps and update debian changelog
        run: |
          sudo apt-get update
          sudo apt-get install devscripts
          debchange -v ${{ needs.get_version.outputs.version }}-${{ matrix.dist }} -b -M --distribution ${{ matrix.dist }} "ci build"

      - name: Build deb packages
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          apt-opts: --install-recommends
          docker-image: "debian:${{ matrix.dist }}-slim"
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: git

      - name: Upload deb files
        uses: actions/upload-artifact@v7
        with:
          name: "redis-ipc_${{ needs.get_version.outputs.version }}-${{ matrix.dist }}"
          path: ./debian/artifacts/*.deb

  create_release:
    name: Create Release
    needs: [packaging, get_version]
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check github variables
        env:
          VERSION: ${{ needs.get_version.outputs.version }}
        run: |
          echo "Package version from git: ${VERSION}"
          git archive --format=tar.gz -o redis-ipc-$VERSION.tar.gz --prefix=redis-ipc-$VERSION/ v${VERSION}

      # download all artifacts to named path
      - uses: actions/download-artifact@v8
        with:
          path: packages
          pattern: redis-ipc*
          merge-multiple: true

      - name: check artifacts
        run: |
          ls -l packages/

      - name: Generate changes file
        uses: sarnold/gitchangelog-action@915234f151ceffb7a8c4f76de77e4ae321087b8f  # v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: CHANGES.md
          draft: false
          prerelease: false
          files: |
            packages/*.deb
            redis-ipc*.tar.gz
