name: smoke

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Environment
      run: |
        echo $GITHUB_ENV
        bash -c set

    - name: Backports
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y -s ppa:nerdboy/embedded
        sudo apt-get install -y libjson-c-dev

    - name: Upstream
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libjson-c-dev

    - name: Common dependencies
      run: |
        sudo apt-get install -y libhiredis-dev autoconf automake autopoint
        sudo apt-get install -y redis-tools redis-server

    - name: Configure
      run: ./autogen.sh

    - name: Build
      run: make

    - name: Message bus
      run: |
        mkdir -p /tmp/redis-ipc
        redis-server --port 0 --pidfile /run/redis.pid --unixsocket /tmp/redis-ipc/socket --unixsocketperm 600 &

    - name: Test
      run: |
        make check

    - name: Cleanup
      run: |
        killall redis-server
