name: smoke

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        include:
          - os: 'ubuntu-20.04'
            test_cmd: 'auto'
          - os: 'ubuntu-18.04'
            test_cmd: 'bionic'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Environment
      run: |
        bash -c set

    # use gtest/gmock 1.10 from PPA in the following step
    - name: Deps plus PPA/msg bus
      run: |
        sudo apt-get -qq update
        sudo apt-get install -yqq software-properties-common libhiredis-dev
        sudo apt-get install -yqq redis-server autoconf automake
        sudo add-apt-repository -y -s ppa:nerdboy/embedded
        sudo apt-get -qq update
        sudo apt-get install -yqq libjson-c-dev libgtest-dev libgmock-dev lcov
        sudo systemctl stop redis

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test
      run: |
        tox -e "${{ matrix.test_cmd }}"

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-18.04'
      with:
        name: coverage
        path: ./coverage

  check:
    name: Collect metrics
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: sarnold/cccc-action@0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_dirs: |
          src
          inc

    - uses: actions/upload-artifact@v2
      with:
        name: metrics
        path: ./metrics
