name: smoke

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Environment
      run: |
        echo $GITHUB_ENV
        bash -c set

    - name: Dependencies
      run: |
        sudo apt-get install -y libhiredis-dev libjson-c-dev autopoint
        sudo apt-get install -y redis-tools redis-server autoconf automake

    - name: Configure
      run: ./autogen.sh

    - name: Build
      run: make

    - name: Message bus
      run: |
        mkdir -p /tmp/redis-ipc
        redis-server --port 0 --pidfile /run/redis.pid --unixsocket /tmp/redis-ipc/socket --unixsocketperm 600 &

    - name: Test
      run: |
        make check

    - name: Cleanup
      run: |
        killall redis-server
